/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrucksIndexRouteImport } from './routes/_authenticated/trucks/index'
import { Route as AuthenticatedTransportersIndexRouteImport } from './routes/_authenticated/transporters/index'
import { Route as AuthenticatedRoleIndexRouteImport } from './routes/_authenticated/$role/index'
import { Route as AuthenticatedTransportersTransporterIdRouteImport } from './routes/_authenticated/transporters/$transporterId'
import { Route as AuthenticatedRoleModuleRouteImport } from './routes/_authenticated/$role/$module'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrucksIndexRoute =
  AuthenticatedTrucksIndexRouteImport.update({
    id: '/trucks/',
    path: '/trucks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportersIndexRoute =
  AuthenticatedTransportersIndexRouteImport.update({
    id: '/transporters/',
    path: '/transporters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleIndexRoute = AuthenticatedRoleIndexRouteImport.update({
  id: '/$role/',
  path: '/$role/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportersTransporterIdRoute =
  AuthenticatedTransportersTransporterIdRouteImport.update({
    id: '/transporters/$transporterId',
    path: '/transporters/$transporterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleModuleRoute = AuthenticatedRoleModuleRouteImport.update({
  id: '/$role/$module',
  path: '/$role/$module',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$role/$module': typeof AuthenticatedRoleModuleRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/$role/': typeof AuthenticatedRoleIndexRoute
  '/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/$role/$module': typeof AuthenticatedRoleModuleRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/$role': typeof AuthenticatedRoleIndexRoute
  '/transporters': typeof AuthenticatedTransportersIndexRoute
  '/trucks': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$role/$module': typeof AuthenticatedRoleModuleRoute
  '/_authenticated/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/_authenticated/$role/': typeof AuthenticatedRoleIndexRoute
  '/_authenticated/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/_authenticated/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$role/$module'
    | '/transporters/$transporterId'
    | '/$role/'
    | '/transporters/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/$role/$module'
    | '/transporters/$transporterId'
    | '/$role'
    | '/transporters'
    | '/trucks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/$role/$module'
    | '/_authenticated/transporters/$transporterId'
    | '/_authenticated/$role/'
    | '/_authenticated/transporters/'
    | '/_authenticated/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks/': {
      id: '/_authenticated/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof AuthenticatedTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/': {
      id: '/_authenticated/transporters/'
      path: '/transporters'
      fullPath: '/transporters/'
      preLoaderRoute: typeof AuthenticatedTransportersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$role/': {
      id: '/_authenticated/$role/'
      path: '/$role'
      fullPath: '/$role/'
      preLoaderRoute: typeof AuthenticatedRoleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/$transporterId': {
      id: '/_authenticated/transporters/$transporterId'
      path: '/transporters/$transporterId'
      fullPath: '/transporters/$transporterId'
      preLoaderRoute: typeof AuthenticatedTransportersTransporterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$role/$module': {
      id: '/_authenticated/$role/$module'
      path: '/$role/$module'
      fullPath: '/$role/$module'
      preLoaderRoute: typeof AuthenticatedRoleModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRoleModuleRoute: typeof AuthenticatedRoleModuleRoute
  AuthenticatedTransportersTransporterIdRoute: typeof AuthenticatedTransportersTransporterIdRoute
  AuthenticatedRoleIndexRoute: typeof AuthenticatedRoleIndexRoute
  AuthenticatedTransportersIndexRoute: typeof AuthenticatedTransportersIndexRoute
  AuthenticatedTrucksIndexRoute: typeof AuthenticatedTrucksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRoleModuleRoute: AuthenticatedRoleModuleRoute,
  AuthenticatedTransportersTransporterIdRoute:
    AuthenticatedTransportersTransporterIdRoute,
  AuthenticatedRoleIndexRoute: AuthenticatedRoleIndexRoute,
  AuthenticatedTransportersIndexRoute: AuthenticatedTransportersIndexRoute,
  AuthenticatedTrucksIndexRoute: AuthenticatedTrucksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
