import { type ModuleField, type ModuleRegistry } from './types'
import { BadgeCheck, Clock, FileText, IdCard, Route, Truck, TrendingUp } from 'lucide-react'

const STATUS = [
  { label: 'Actif', value: 'active' },
  { label: 'En attente', value: 'pending' },
  { label: 'Clôturé', value: 'closed' },
  { label: 'Anomalie', value: 'anomaly' },
]

const SYNC = [
  { label: 'Synchronisé', value: 'synced' },
  { label: 'En attente', value: 'pending' },
  { label: 'Hors-ligne', value: 'offline' },
]

const RISK = [
  { label: 'Faible', value: 'low' },
  { label: 'Moyen', value: 'medium' },
  { label: 'Élevé', value: 'high' },
]

const RECONCILIATION_STATUS = [
  { label: 'En attente', value: 'pending' },
  { label: 'Vérifiée', value: 'verified' },
  { label: 'Redressement appliqué', value: 'redressement_applied' },
]

const REDRESSEMENT_STATUS = [
  { label: 'Émis', value: 'issued' },
  { label: 'Payé', value: 'paid' },
  { label: 'Annulé', value: 'waived' },
]

const MARKETEUR_FIELDS: ModuleField[] = [
  { key: 'name', header: 'Marketeur', type: 'text', filterable: true },
  { key: 'quota', header: 'Quota (kg)', type: 'number' },
  {
    key: 'status',
    header: 'Statut',
    type: 'status',
    options: STATUS,
    filterable: true,
  },
  { key: 'declared_at', header: 'Déclaration', type: 'date' },
]

export const MODULE_REGISTRY: ModuleRegistry = {
  // ---------- SUPER_ADMIN ----------
  'SUPERADMIN:overview': {
    title: "Vue d'ensemble nationale",
    description: 'KPIs nationaux, volumes, traçabilité et anomalies agrégées.',
    mockCount: 20,
    fields: [
      { key: 'region', header: 'Région', type: 'text', filterable: true },
      { key: 'traceability', header: 'Traçabilité %', type: 'number' },
      { key: 'volume', header: 'Volume (t)', type: 'number' },
      { key: 'anomalies', header: 'Anomalies', type: 'number' },
      { key: 'updated_at', header: 'Mis à jour', type: 'date' },
    ],
  },
  'SUPERADMIN:map': {
    title: 'Carte interactive',
    description: 'Vue cartographique nationale des sites, tournées et anomalies.',
    mockCount: 18,
    fields: [
      { key: 'site', header: 'Site', type: 'text', filterable: true },
      { key: 'region', header: 'Région', type: 'text', filterable: true },
      { key: 'status', header: 'Statut', type: 'status', options: STATUS, filterable: true },
      { key: 'updated_at', header: 'Mis à jour', type: 'date' },
    ],
  },
  'SUPERADMIN:finance': {
    title: 'Indicateurs financiers',
    description: 'Subventions, écarts et économies réalisées.',
    mockCount: 20,
    fields: [
      { key: 'org', header: 'Organisation', type: 'text', filterable: true },
      { key: 'subsidy', header: 'Subvention', type: 'currency' },
      { key: 'gap', header: 'Écart', type: 'currency' },
      { key: 'saved', header: 'Économies', type: 'currency' },
      { key: 'period', header: 'Période', type: 'date' },
    ],
  },
  'SUPERADMIN:transporters': {
    title: 'Transporteurs',
    description: 'Parc transporteurs, contrats et validations externes.',
    mockCount: 24,
    fields: [
      { key: 'name', header: 'Transporteur', type: 'text', filterable: true },
      { key: 'contracts', header: 'Contrats actifs', type: 'number' },
      { key: 'vehicles', header: 'Véhicules', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'updated_at', header: 'Modifié le', type: 'date' },
    ],
  },
  'SUPERADMIN:marketeurs': {
    title: 'Marketeurs',
    description: 'Suivi national des marketeurs et indicateurs agrégés.',
    mockCount: 26,
    fields: MARKETEUR_FIELDS,
  },
  'SUPERADMIN:organizations': {
    title: 'Organisations & sites',
    description: 'Toutes les organisations et leurs sites localisés.',
    mockCount: 30,
    fields: [
      { key: 'name', header: 'Organisation', type: 'text', filterable: true },
      {
        key: 'type',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'Regulator', value: 'REGULATEUR' },
          { label: 'Depot', value: 'DEPOT' },
          { label: 'Marketeur', value: 'MARKETEUR' },
          { label: 'Transporteur', value: 'TRANSPORTEUR' },
          { label: 'Client', value: 'CLIENT' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'sites', header: 'Sites', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
      },
      { key: 'created_at', header: 'Créé le', type: 'date' },
    ],
  },
  'SUPERADMIN:users': {
    title: 'Utilisateurs (RBAC)',
    description: 'Gestion des utilisateurs et rôles.',
    mockCount: 40,
    fields: [
      { key: 'name', header: 'Nom', type: 'text', filterable: true },
      { key: 'email', header: 'Email', type: 'text' },
      {
        key: 'role',
        header: 'Rôle',
        type: 'badge',
        options: [
          { label: 'Super Admin', value: 'SUPERADMIN' },
          { label: 'Admin', value: 'ADMIN' },
          { label: 'Superviseur', value: 'SUPERVISOR' },
          { label: 'Intégrateur', value: 'INTEGRATEUR' },
          { label: 'Agent', value: 'AGENT' },
          { label: 'Marketeur', value: 'MARKETEUR' },
          { label: 'Transporteur', value: 'TRANSPORTEUR' },
        ],
        filterable: true,
        groupable: true,
      },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
      },
      { key: 'last_login_at', header: 'Dernière connexion', type: 'date' },
    ],
  },
  'SUPERADMIN:tours': {
    title: 'Tournées',
    description: 'Tournées de livraison/approvisionnement.',
    mockCount: 36,
    fields: [
      { key: 'ref', header: 'Tournée', type: 'text', filterable: true },
      { key: 'type', header: 'Type', type: 'badge', options: [{ label: 'VRAC', value: 'vrac' }, { label: '50kg', value: 'bottles' }], filterable: true, groupable: true },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Brouillon', value: 'draft' },
          { label: 'Planifiée', value: 'planned' },
          { label: 'En cours', value: 'INPROGRESS' },
          { label: 'Clôturée', value: 'closed' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'started_at', header: 'Début', type: 'date' },
    ],
  },
  'SUPERADMIN:deliveries': {
    title: 'Livraisons',
    description: 'Suivi des livraisons et points de contrôle.',
    mockCount: 32,
    fields: [
      { key: 'ref', header: 'Livraison', type: 'text', filterable: true },
      { key: 'tour', header: 'Tournée', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'checkpoint', header: 'Checkpoint', type: 'text' },
      { key: 'completedAt', header: 'Complété le', type: 'date' },
    ],
  },
  'SUPERADMIN:declarations': {
    title: 'Déclarations',
    description: 'Déclarations de ventes marketeurs.',
    mockCount: 28,
    fields: [
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'period', header: 'Période', type: 'text' },
      { key: 'declared_volume', header: 'Volume déclaré', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Brouillon', value: 'draft' },
          { label: 'Soumise', value: 'submitted' },
          { label: 'Réconciliée', value: 'reconciled' },
          { label: 'Contestée', value: 'disputed' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'submitted_at', header: 'Soumis le', type: 'date' },
    ],
  },
  'SUPERADMIN:reconciliations': {
    title: 'Réconciliations',
    description: 'Écarts déclarés vs scannés et suivi de péréquation.',
    mockCount: 26,
    fields: [
      { key: 'declaration', header: 'Déclaration', type: 'text', filterable: true },
      { key: 'tracked_volume', header: 'Volume tracké', type: 'number' },
      { key: 'volume_gap', header: 'Écart volume', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: RECONCILIATION_STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'verified_at', header: 'Vérifié le', type: 'date' },
    ],
  },
  'SUPERADMIN:redressements': {
    title: 'Redressements',
    description: 'Suivi des redressements financiers.',
    mockCount: 24,
    fields: [
      { key: 'reconciliation', header: 'Réconciliation', type: 'text', filterable: true },
      { key: 'amount', header: 'Montant FCFA', type: 'currency' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: REDRESSEMENT_STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'issued_at', header: 'Émis le', type: 'date' },
      { key: 'paid_at', header: 'Payé le', type: 'date' },
    ],
  },
  'SUPERADMIN:anomalies': {
    title: 'Anomalies & fraude',
    description: 'Détection par régression linéaire et écarts déclarés/scannés.',
    mockCount: 35,
    fields: [
      { key: 'subject', header: 'Sujet', type: 'text', filterable: true },
      {
        key: 'type',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'Volume déclaré', value: 'volume' },
          { label: 'Déviation trajet', value: 'deviation' },
          { label: 'Scan hors séquence', value: 'scan' },
        ],
        filterable: true,
        groupable: true,
      },
      {
        key: 'risk',
        header: 'Risque',
        type: 'status',
        options: RISK,
        filterable: true,
      },
      { key: 'detected_at', header: 'Détecté le', type: 'date' },
    ],
  },
  'SUPERADMIN:incidents': {
    title: 'Incidents',
    description: 'Incidents opérationnels et actions correctives.',
    mockCount: 22,
    fields: [
      { key: 'title', header: 'Incident', type: 'text', filterable: true },
      { key: 'owner', header: 'Responsable', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'raisedAt', header: 'Déclaré le', type: 'date' },
    ],
  },
  'SUPERADMIN:risks': {
    title: 'Scores de risque',
    description: 'Scoring par marketeur, transporteur et livreur.',
    mockCount: 26,
    fields: [
      { key: 'entity', header: 'Entité', type: 'text', filterable: true },
      {
        key: 'kind',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'Marketeur', value: 'marketeur' },
          { label: 'Transporteur', value: 'transporteur' },
          { label: 'Livreur', value: 'livreur' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'score', header: 'Score', type: 'number' },
      {
        key: 'level',
        header: 'Niveau',
        type: 'status',
        options: RISK,
        filterable: true,
      },
      { key: 'calculatedAt', header: 'Calculé le', type: 'date' },
    ],
  },
  'SUPERADMIN:custom-roles': {
    title: 'Rôles personnalisés',
    description: 'Gestion des rôles et permissions personnalisés.',
    mockCount: 15,
    fields: [
      { key: 'name', header: 'Rôle', type: 'text', filterable: true },
      { key: 'permissions', header: 'Permissions', type: 'number' },
      { key: 'users', header: 'Utilisateurs', type: 'number' },
      { key: 'created_at', header: 'Créé le', type: 'date' },
    ],
  },
  'SUPERADMIN:delivery-types': {
    title: 'Types de livraison',
    description: 'Configuration des modes de livraison.',
    mockCount: 12,
    fields: [
      { key: 'name', header: 'Type', type: 'text', filterable: true },
      { key: 'description', header: 'Description', type: 'text' },
      {
        key: 'active',
        header: 'Actif',
        type: 'badge',
        options: [
          { label: 'Oui', value: 'yes' },
          { label: 'Non', value: 'no' },
        ],
        filterable: true,
      },
    ],
  },
  'SUPERADMIN:tour-statuses': {
    title: 'Statuts de tournée',
    description: 'Configuration des statuts de tournée.',
    mockCount: 10,
    fields: [
      { key: 'name', header: 'Statut', type: 'text', filterable: true },
      { key: 'description', header: 'Description', type: 'text' },
      { key: 'order', header: 'Ordre', type: 'number' },
      { key: 'color', header: 'Couleur', type: 'text' },
    ],
  },
  'SUPERADMIN:vehicle-types': {
    title: 'Types de véhicule',
    description: 'Configuration des types de véhicules de la flotte.',
    mockCount: 14,
    fields: [
      { key: 'name', header: 'Type', type: 'text', filterable: true },
      { key: 'capacity', header: 'Capacité (kg)', type: 'number' },
      {
        key: 'active',
        header: 'Actif',
        type: 'badge',
        options: [
          { label: 'Oui', value: 'yes' },
          { label: 'Non', value: 'no' },
        ],
        filterable: true,
      },
    ],
  },
  'SUPERADMIN:reports': {
    title: 'Rapports & exports',
    description: 'Rapports opérationnels, conformité et financiers.',
    mockCount: 25,
    fields: [
      { key: 'title', header: 'Rapport', type: 'text', filterable: true },
      {
        key: 'category',
        header: 'Catégorie',
        type: 'badge',
        options: [
          { label: 'Opérationnel', value: 'ops' },
          { label: 'Conformité', value: 'compliance' },
          { label: 'Financier', value: 'finance' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'generated_at', header: 'Généré le', type: 'date' },
    ],
  },
  'SUPERADMIN:audit-logs': {
    title: "Journal d'audit",
    description: 'Traçabilité des actions utilisateurs.',
    mockCount: 50,
    fields: [
      { key: 'action', header: 'Action', type: 'text', filterable: true },
      { key: 'user', header: 'Utilisateur', type: 'text', filterable: true },
      {
        key: 'resource',
        header: 'Ressource',
        type: 'badge',
        options: [
          { label: 'Utilisateur', value: 'user' },
          { label: 'Organisation', value: 'org' },
          { label: 'Déclaration', value: 'declaration' },
          { label: 'Tournée', value: 'tour' },
          { label: 'Rôle', value: 'role' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'timestamp', header: 'Horodatage', type: 'date' },
    ],
  },
  'SUPERADMIN:settings': {
    title: 'Paramètres',
    description: 'Paramètres généraux du système et seuils opérationnels.',
    mockCount: 18,
    fields: [
      { key: 'key', header: 'Clé', type: 'text', filterable: true },
      { key: 'value', header: 'Valeur', type: 'text' },
      { key: 'category', header: 'Catégorie', type: 'text', filterable: true, groupable: true },
      { key: 'updated_at', header: 'Modifié le', type: 'date' },
    ],
  },
  'SUPERADMIN:system-health': {
    title: 'Santé du système',
    description: 'État des services, bases et files événementielles.',
    mockCount: 14,
    fields: [
      { key: 'service', header: 'Service', type: 'text', filterable: true },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'OK', value: 'ok' },
          { label: 'Dégradé', value: 'degraded' },
          { label: 'KO', value: 'down' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'latency', header: 'Latence', type: 'number' },
      { key: 'checked_at', header: 'Vérifié le', type: 'date' },
    ],
  },

  // ---------- ADMIN ----------
  'ADMIN:users': {
    title: 'Utilisateurs & organisations',
    description: 'Administration des comptes et entités.',
    mockCount: 35,
    fields: [
      { key: 'name', header: 'Nom', type: 'text', filterable: true },
      { key: 'org', header: 'Organisation', type: 'text', filterable: true },
      {
        key: 'role',
        header: 'Rôle',
        type: 'badge',
        options: [
          { label: 'Agent', value: 'AGENT' },
          { label: 'Marketeur', value: 'MARKETEUR' },
          { label: 'Transporteur', value: 'TRANSPORTEUR' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'status', header: 'Statut', type: 'status', options: STATUS, filterable: true },
      { key: 'updated_at', header: 'Modifié le', type: 'date' },
    ],
  },
  'ADMIN:marketeurs': {
    title: 'Marketeurs',
    description: 'Suivi des marketeurs par l’administration CSPH.',
    mockCount: 28,
    fields: MARKETEUR_FIELDS,
  },
  'ADMIN:declarations': {
    title: 'Déclarations à valider',
    description: 'Déclarations de ventes en attente de validation.',
    mockCount: 30,
    fields: [
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'volume', header: 'Volume (kg)', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'submitted_at', header: 'Soumis le', type: 'date' },
    ],
  },
  'ADMIN:reports': {
    title: 'Rapports de conformité',
    description: 'Rapports opérationnels et indicateurs de conformité.',
    mockCount: 24,
    fields: [
      { key: 'title', header: 'Rapport', type: 'text', filterable: true },
      { key: 'owner', header: 'Émetteur', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'generated_at', header: 'Généré le', type: 'date' },
    ],
  },
  'ADMIN:alert-rules': {
    title: 'Règles d’alerte',
    description: 'Paramétrage des seuils et conditions.',
    mockCount: 18,
    fields: [
      { key: 'name', header: 'Règle', type: 'text', filterable: true },
      {
        key: 'severity',
        header: 'Sévérité',
        type: 'status',
        options: RISK,
        filterable: true,
        groupable: true,
      },
      { key: 'updated_at', header: 'Modifié le', type: 'date' },
    ],
  },

  // ---------- SUPERVISOR ----------
  'SUPERVISOR:overview': {
    title: 'Métriques système',
    description: 'Vue consolidée des métriques opérationnelles.',
    mockCount: 22,
    fields: [
      { key: 'metric', header: 'Métrique', type: 'text', filterable: true },
      { key: 'value', header: 'Valeur', type: 'number' },
      { key: 'unit', header: 'Unité', type: 'text' },
      { key: 'checked_at', header: 'Vérifié le', type: 'date' },
    ],
  },
  'SUPERVISOR:infra': {
    title: 'Dashboards infra (Grafana)',
    description: '8 dashboards dédiés — Prometheus, CPU, mémoire, réseau.',
    mockCount: 22,
    fields: [
      { key: 'dashboard', header: 'Dashboard', type: 'text', filterable: true },
      {
        key: 'health',
        header: 'Santé',
        type: 'status',
        options: [
          { label: 'OK', value: 'ok' },
          { label: 'Dégradé', value: 'degraded' },
          { label: 'Critique', value: 'critical' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'cpu', header: 'CPU %', type: 'number' },
      { key: 'checked_at', header: 'Vérifié le', type: 'date' },
    ],
  },
  'SUPERVISOR:risk': {
    title: 'Scores de risque',
    description: 'Scoring par marketeur, transporteur et livreur.',
    mockCount: 26,
    fields: [
      { key: 'entity', header: 'Entité', type: 'text', filterable: true },
      {
        key: 'kind',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'Marketeur', value: 'marketeur' },
          { label: 'Transporteur', value: 'transporteur' },
          { label: 'Livreur', value: 'livreur' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'score', header: 'Score', type: 'number' },
      {
        key: 'level',
        header: 'Niveau',
        type: 'status',
        options: RISK,
        filterable: true,
      },
    ],
  },
  'SUPERVISOR:logs': {
    title: 'Logs centralisés',
    description: 'Traçabilité technique et corrélation de requêtes.',
    mockCount: 45,
    fields: [
      { key: 'service', header: 'Service', type: 'text', filterable: true },
      {
        key: 'level',
        header: 'Niveau',
        type: 'status',
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Warn', value: 'warn' },
          { label: 'Error', value: 'error' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'message', header: 'Message', type: 'text' },
      { key: 'at', header: 'Horodatage', type: 'date' },
    ],
  },
  'SUPERVISOR:alerts': {
    title: 'Alertes infrastructure',
    description: 'Alertes techniques routées vers le SUPERVISOR.',
    mockCount: 30,
    fields: [
      { key: 'title', header: 'Alerte', type: 'text', filterable: true },
      {
        key: 'severity',
        header: 'Sévérité',
        type: 'status',
        options: RISK,
        filterable: true,
        groupable: true,
      },
      { key: 'raisedAt', header: 'Déclenchée le', type: 'date' },
    ],
  },

  // ---------- INTEGRATEUR ----------
  'INTEGRATEUR:overview': {
    title: 'Activation matériel',
    description: 'Vue d’ensemble du matériel IoT et activations récentes.',
    mockCount: 24,
    fields: [
      { key: 'serial', header: 'N° série', type: 'text', filterable: true },
      { key: 'deviceType', header: 'Type', type: 'text', filterable: true, groupable: true },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
      },
      { key: 'activated_at', header: 'Activé le', type: 'date' },
    ],
  },
  'INTEGRATEUR:pda': {
    title: 'PDA + GPS + RFID',
    description: 'Parc de terminaux PDA et modules IoT.',
    mockCount: 32,
    fields: [
      { key: 'serial', header: 'N° série', type: 'text', filterable: true },
      {
        key: 'model',
        header: 'Modèle',
        type: 'badge',
        options: [
          { label: 'PDA-UHF', value: 'pda-uhf' },
          { label: 'GPS-T', value: 'gps-t' },
          { label: 'RFID-R', value: 'rfid-r' },
        ],
        filterable: true,
        groupable: true,
      },
      {
        key: 'sync',
        header: 'Synchro',
        type: 'status',
        options: SYNC,
        filterable: true,
      },
      { key: 'activated_at', header: 'Activé le', type: 'date' },
    ],
  },
  'INTEGRATEUR:auth': {
    title: 'Authentification',
    description: 'Activation et authentification des appareils.',
    mockCount: 20,
    fields: [
      { key: 'device', header: 'Appareil', type: 'text', filterable: true },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
      },
      { key: 'enrolledAt', header: 'Enrôlé le', type: 'date' },
    ],
  },
  'INTEGRATEUR:fleet-iot': {
    title: 'Parc équipements',
    description: 'Maintenance matériel PDA, GPS, RFID.',
    mockCount: 30,
    fields: [
      { key: 'asset', header: 'Équipement', type: 'text', filterable: true },
      {
        key: 'state',
        header: 'État',
        type: 'status',
        options: [
          { label: 'Opérationnel', value: 'ok' },
          { label: 'Batterie faible', value: 'lowbattery' },
          { label: 'Défaillance', value: 'failure' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'lastSeen', header: 'Vu le', type: 'date' },
    ],
  },
  'INTEGRATEUR:logs': {
    title: 'Logs maintenance',
    description: 'Suivi des interventions et maintenances.',
    mockCount: 26,
    fields: [
      { key: 'asset', header: 'Équipement', type: 'text', filterable: true },
      { key: 'action', header: 'Action', type: 'text' },
      { key: 'performedBy', header: 'Technicien', type: 'text' },
      { key: 'performedAt', header: 'Effectué le', type: 'date' },
    ],
  },

  // ---------- AGENT ----------
  'AGENT:overview': {
    title: 'Vue consolidée',
    description: 'Tableau de bord agent : marketeurs, déclarations et anomalies.',
    mockCount: 22,
    fields: [
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'pending', header: 'En attente', type: 'number' },
      { key: 'anomalies', header: 'Anomalies', type: 'number' },
      { key: 'updated_at', header: 'Mis à jour', type: 'date' },
    ],
  },
  'AGENT:marketeurs': {
    title: 'Marketeurs',
    description: 'Vue consolidée des marketeurs assignés.',
    mockCount: 24,
    fields: MARKETEUR_FIELDS,
  },
  'AGENT:declarations': {
    title: 'Déclarations en attente',
    description: 'Déclarations à valider pour vos marketeurs.',
    mockCount: 28,
    fields: [
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'volume', header: 'Volume (kg)', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
      { key: 'submitted_at', header: 'Soumis le', type: 'date' },
    ],
  },
  'AGENT:visits': {
    title: 'Rapports de visite',
    description: 'Comptes-rendus de visite terrain.',
    mockCount: 22,
    fields: [
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'agent', header: 'Agent', type: 'text' },
      { key: 'visitAt', header: 'Visite le', type: 'date' },
    ],
  },
  'AGENT:passwords': {
    title: 'Réinitialisation mots de passe',
    description: 'Reset des mots de passe marketeurs et chauffeurs.',
    mockCount: 18,
    fields: [
      { key: 'user', header: 'Utilisateur', type: 'text', filterable: true },
      { key: 'role', header: 'Rôle', type: 'badge', options: [{ label: 'Transporteur', value: 'TRANSPORTEUR' }, { label: 'Marketeur', value: 'MARKETEUR' }], filterable: true, groupable: true },
      { key: 'resetAt', header: 'Réinitialisé le', type: 'date' },
    ],
  },
  'AGENT:anomalies': {
    title: 'Anomalies à investiguer',
    description: 'Alertes métier routées vers les AGENT.',
    mockCount: 26,
    fields: [
      { key: 'subject', header: 'Sujet', type: 'text', filterable: true },
      {
        key: 'severity',
        header: 'Sévérité',
        type: 'status',
        options: RISK,
        filterable: true,
        groupable: true,
      },
      { key: 'raisedAt', header: 'Déclenchée le', type: 'date' },
    ],
  },
  'AGENT:site-verification': {
    title: 'Vérification des Sites',
    description: 'Validation terrain des sites de distribution.',
    mockCount: 22,
    fields: [
      { key: 'site', header: 'Site', type: 'text', filterable: true },
      { key: 'address', header: 'Adresse', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Vérifié', value: 'verified' },
          { label: 'En attente', value: 'pending' },
          { label: 'Rejeté', value: 'rejected' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'verified_by', header: 'Vérifié par', type: 'text' },
      { key: 'verified_at', header: 'Vérifié le', type: 'date' },
    ],
  },

  // ---------- MARKETEUR ----------
  'MARKETEUR:trucks': {
    title: 'Camions & chauffeurs',
    description: 'État de la flotte et affectation des chauffeurs.',
    mockCount: 30,
    fields: [
      { key: 'plate', header: 'Immatriculation', type: 'text', filterable: true },
      { key: 'driver', header: 'Chauffeur', type: 'text' },
      { key: 'capacity', header: 'Capacité (kg)', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Disponible', value: 'available' },
          { label: 'En tournée', value: 'on_tour' },
          { label: 'Maintenance', value: 'maintenance' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'updated_at', header: 'Modifié le', type: 'date' },
    ],
  },
  'MARKETEUR:quotas': {
    title: 'Quotas & volumes',
    description: 'Quotas alloués et volumes commercialisés.',
    mockCount: 20,
    fields: [
      { key: 'period', header: 'Période', type: 'text', filterable: true },
      { key: 'allocated', header: 'Alloué (kg)', type: 'number' },
      { key: 'sold', header: 'Vendu (kg)', type: 'number' },
      { key: 'remaining', header: 'Reste (kg)', type: 'number' },
    ],
  },
  'MARKETEUR:supply': {
    title: 'Requêtes d’enlèvement',
    description: 'Flux d’approvisionnement en vrac (Gaz Vrac).',
    mockCount: 28,
    fields: [
      { key: 'ref', header: 'Référence', type: 'text', filterable: true },
      { key: 'source', header: 'Source', type: 'text', filterable: true },
      { key: 'qty', header: 'Quantité (kg)', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Demandée', value: 'requested' },
          { label: 'Chargée', value: 'loaded' },
          { label: 'Livrée', value: 'delivered' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'requestedAt', header: 'Demandée le', type: 'date' },
    ],
  },
  'MARKETEUR:delivery-tours': {
    title: 'Tournées de livraison',
    description: 'Tournées de bouteilles 50 kg et vrac vers clients.',
    mockCount: 32,
    fields: [
      { key: 'ref', header: 'Tournée', type: 'text', filterable: true },
      { key: 'driver', header: 'Chauffeur', type: 'text' },
      { key: 'checkpoints', header: 'Checkpoints', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Planifiée', value: 'planned' },
          { label: 'En cours', value: 'running' },
          { label: 'Clôturée', value: 'closed' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'date', header: 'Date', type: 'date' },
    ],
  },
  'MARKETEUR:clients': {
    title: 'Clients & livraisons',
    description: 'Historique des livraisons par client.',
    mockCount: 35,
    fields: [
      { key: 'name', header: 'Client', type: 'text', filterable: true },
      { key: 'city', header: 'Ville', type: 'text', filterable: true },
      { key: 'orders', header: 'Commandes', type: 'number' },
      { key: 'lastOrder', header: 'Dernière commande', type: 'date' },
    ],
  },
  'MARKETEUR:performance': {
    title: 'Performance chauffeurs',
    description: 'Indicateurs de performance des chauffeurs/livreurs.',
    mockCount: 24,
    fields: [
      { key: 'driver', header: 'Chauffeur', type: 'text', filterable: true },
      { key: 'tours', header: 'Tournées', type: 'number' },
      { key: 'onTime', header: 'À l’heure %', type: 'number' },
      { key: 'rating', header: 'Note', type: 'number' },
    ],
  },
  'MARKETEUR:reports': {
    title: 'Rapports',
    description: 'Rapports opérationnels et financiers.',
    mockCount: 20,
    fields: [
      { key: 'title', header: 'Rapport', type: 'text', filterable: true },
      {
        key: 'category',
        header: 'Catégorie',
        type: 'badge',
        options: [
          { label: 'Opérationnel', value: 'ops' },
          { label: 'Financier', value: 'finance' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'generated_at', header: 'Généré le', type: 'date' },
    ],
  },

  // ---------- TRANSPORTEUR ----------
  'TRANSPORTEUR:tours-pending': {
    title: 'Tournées en attente d’accusé',
    description: 'Tournées EXTERNAL en PENDINGTRANSPORTERACK — à relever.',
    icon: Route,
    mockCount: 3,
    fields: [
      { key: 'ref', header: 'Tournée', type: 'text', filterable: true },
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      {
        key: 'type',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'VRAC', value: 'vrac' },
          { label: '50kg', value: 'bottles' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'driver', header: 'Chauffeur', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [{ label: 'En attente', value: 'pending_ack' }],
        filterable: true,
        groupable: true,
      },
      { key: 'created_at', header: 'Créée le', type: 'date' },
    ],
  },
  'TRANSPORTEUR:tours-active': {
    title: 'Tournées actives',
    description: 'Tournées ACKNOWLEDGED ou INPROGRESS — en cours de livraison.',
    icon: Route,
    mockCount: 5,
    fields: [
      { key: 'ref', header: 'Tournée', type: 'text', filterable: true },
      { key: 'client', header: 'Client', type: 'text', filterable: true },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Accusée', value: 'acknowledged' },
          { label: 'En cours', value: 'INPROGRESS' },
          { label: 'Checkpoint actif', value: 'checkpoint_active' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'progress', header: 'Avancement', type: 'number' },
      { key: 'started_at', header: 'Début', type: 'date' },
    ],
  },
  'TRANSPORTEUR:tours-history': {
    title: 'Historique des tournées',
    description: 'Tournées clôturées — récapitulatif des livraisons.',
    icon: Clock,
    mockCount: 40,
    fields: [
      { key: 'ref', header: 'Tournée', type: 'text', filterable: true },
      { key: 'delivered', header: 'Livré (TM)', type: 'number' },
      { key: 'bottles', header: 'Bouteilles', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Clôturée', value: 'closed' },
          { label: 'Annulée', value: 'cancelled' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'closed_at', header: 'Clôturée le', type: 'date' },
    ],
  },
  'TRANSPORTEUR:vehicles': {
    title: 'Camions',
    description: 'Parc camions du transporteur et certificats.',
    icon: Truck,
    mockCount: 18,
    fields: [
      { key: 'plate', header: 'Immatriculation', type: 'text', filterable: true },
      {
        key: 'type',
        header: 'Type',
        type: 'badge',
        options: [
          { label: 'VRAC', value: 'vrac' },
          { label: '50kg', value: 'bottles' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'driver', header: 'Chauffeur', type: 'text' },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: [
          { label: 'Disponible', value: 'available' },
          { label: 'En tournée', value: 'on_tour' },
          { label: 'Maintenance', value: 'maintenance' },
        ],
        filterable: true,
        groupable: true,
      },
      { key: 'certExpiry', header: 'Certificat expire le', type: 'date' },
    ],
  },
  'TRANSPORTEUR:drivers': {
    title: 'Chauffeurs',
    description: 'Chauffeurs rattachés au transporteur.',
    icon: IdCard,
    mockCount: 24,
    fields: [
      { key: 'name', header: 'Chauffeur', type: 'text', filterable: true },
      { key: 'license', header: 'Permis', type: 'text' },
      { key: 'licenseExpiry', header: 'Permis expire le', type: 'date' },
      {
        key: 'status',
        header: 'Statut',
        type: 'badge',
        options: [
          { label: 'Actif', value: 'active' },
          { label: 'Inactif', value: 'inactive' },
        ],
        filterable: true,
        groupable: true,
      },
    ],
  },
  'TRANSPORTEUR:livreurs': {
    title: 'Livreurs PDA',
    description: 'Opérateurs PDA assignés aux tournées.',
    icon: BadgeCheck,
    mockCount: 16,
    fields: [
      { key: 'name', header: 'Livreur', type: 'text', filterable: true },
      { key: 'activeTour', header: 'Tournée active', type: 'text' },
      { key: 'pda', header: 'PDA', type: 'text' },
      {
        key: 'sync',
        header: 'Synchro',
        type: 'status',
        options: SYNC,
        filterable: true,
      },
      { key: 'lastSeen', header: 'Dernière connexion', type: 'date' },
    ],
  },
  'TRANSPORTEUR:contracts': {
    title: 'Mes contrats',
    description: 'Accord de prestation avec les marketeurs.',
    icon: FileText,
    mockCount: 6,
    fields: [
      { key: 'ref', header: 'Référence', type: 'text', filterable: true },
      { key: 'marketeur', header: 'Marketeur', type: 'text', filterable: true },
      { key: 'period', header: 'Période', type: 'text' },
      {
        key: 'isPrimary',
        header: 'Principal',
        type: 'badge',
        options: [
          { label: 'Oui', value: 'primary' },
          { label: 'Non', value: 'secondary' },
        ],
        filterable: true,
        groupable: true,
      },
      {
        key: 'status',
        header: 'Statut',
        type: 'status',
        options: STATUS,
        filterable: true,
        groupable: true,
      },
    ],
  },
  'TRANSPORTEUR:performance': {
    title: 'Performance',
    description: 'Taux d’achevement des tournées et indicateurs de ponctualité.',
    icon: TrendingUp,
    mockCount: 12,
    fields: [
      { key: 'name', header: 'Chauffeur', type: 'text', filterable: true },
      { key: 'tours', header: 'Tournées', type: 'number' },
      { key: 'onTime', header: 'À l’heure %', type: 'number' },
      { key: 'rating', header: 'Note', type: 'number' },
      {
        key: 'status',
        header: 'Statut',
        type: 'badge',
        options: [
          { label: 'OK', value: 'ok' },
          { label: 'À revoir', value: 'warning' },
        ],
        filterable: true,
        groupable: true,
      },
    ],
  },
}
