/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActivityTripTrackingRouteImport } from './routes/_authenticated/activity/trip-tracking'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedMarketersIndexRouteImport } from './routes/_authenticated/marketers/index'
import { Route as AuthenticatedMarketersMarketerIdRouteImport } from './routes/_authenticated/marketers/$marketerId'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes/index'
import { Route as AuthenticatedTransportersIndexRouteImport } from './routes/_authenticated/transporters/index'
import { Route as AuthenticatedTransportersTransporterIdRouteImport } from './routes/_authenticated/transporters/$transporterId'
import { Route as AuthenticatedTrucksIndexRouteImport } from './routes/_authenticated/trucks/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityTripTrackingRoute =
  AuthenticatedActivityTripTrackingRouteImport.update({
    id: '/activity/trip-tracking',
    path: '/activity/trip-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketersIndexRoute =
  AuthenticatedMarketersIndexRouteImport.update({
    id: '/marketers/',
    path: '/marketers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketersMarketerIdRoute =
  AuthenticatedMarketersMarketerIdRouteImport.update({
    id: '/marketers/$marketerId',
    path: '/marketers/$marketerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/routes/',
    path: '/routes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportersIndexRoute =
  AuthenticatedTransportersIndexRouteImport.update({
    id: '/transporters/',
    path: '/transporters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportersTransporterIdRoute =
  AuthenticatedTransportersTransporterIdRouteImport.update({
    id: '/transporters/$transporterId',
    path: '/transporters/$transporterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrucksIndexRoute =
  AuthenticatedTrucksIndexRouteImport.update({
    id: '/trucks/',
    path: '/trucks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/activity/trip-tracking': typeof AuthenticatedActivityTripTrackingRoute
  '/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/activity/trip-tracking': typeof AuthenticatedActivityTripTrackingRoute
  '/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/marketers': typeof AuthenticatedMarketersIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/transporters': typeof AuthenticatedTransportersIndexRoute
  '/trucks': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activity/trip-tracking': typeof AuthenticatedActivityTripTrackingRoute
  '/_authenticated/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/_authenticated/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/_authenticated/trucks/': typeof AuthenticatedTrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity/trip-tracking'
    | '/marketers/$marketerId'
    | '/transporters/$transporterId'
    | '/dashboard/'
    | '/marketers/'
    | '/routes/'
    | '/transporters/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity/trip-tracking'
    | '/marketers/$marketerId'
    | '/transporters/$transporterId'
    | '/dashboard'
    | '/marketers'
    | '/routes'
    | '/transporters'
    | '/trucks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/activity/trip-tracking'
    | '/_authenticated/marketers/$marketerId'
    | '/_authenticated/transporters/$transporterId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/marketers/'
    | '/_authenticated/routes/'
    | '/_authenticated/transporters/'
    | '/_authenticated/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/trip-tracking': {
      id: '/_authenticated/activity/trip-tracking'
      path: '/activity/trip-tracking'
      fullPath: '/activity/trip-tracking'
      preLoaderRoute: typeof AuthenticatedActivityTripTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketers/': {
      id: '/_authenticated/marketers/'
      path: '/marketers'
      fullPath: '/marketers/'
      preLoaderRoute: typeof AuthenticatedMarketersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketers/$marketerId': {
      id: '/_authenticated/marketers/$marketerId'
      path: '/marketers/$marketerId'
      fullPath: '/marketers/$marketerId'
      preLoaderRoute: typeof AuthenticatedMarketersMarketerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/': {
      id: '/_authenticated/transporters/'
      path: '/transporters'
      fullPath: '/transporters/'
      preLoaderRoute: typeof AuthenticatedTransportersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/$transporterId': {
      id: '/_authenticated/transporters/$transporterId'
      path: '/transporters/$transporterId'
      fullPath: '/transporters/$transporterId'
      preLoaderRoute: typeof AuthenticatedTransportersTransporterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks/': {
      id: '/_authenticated/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof AuthenticatedTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivityTripTrackingRoute: typeof AuthenticatedActivityTripTrackingRoute
  AuthenticatedMarketersMarketerIdRoute: typeof AuthenticatedMarketersMarketerIdRoute
  AuthenticatedTransportersTransporterIdRoute: typeof AuthenticatedTransportersTransporterIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedMarketersIndexRoute: typeof AuthenticatedMarketersIndexRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
  AuthenticatedTransportersIndexRoute: typeof AuthenticatedTransportersIndexRoute
  AuthenticatedTrucksIndexRoute: typeof AuthenticatedTrucksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivityTripTrackingRoute:
    AuthenticatedActivityTripTrackingRoute,
  AuthenticatedMarketersMarketerIdRoute: AuthenticatedMarketersMarketerIdRoute,
  AuthenticatedTransportersTransporterIdRoute:
    AuthenticatedTransportersTransporterIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedMarketersIndexRoute: AuthenticatedMarketersIndexRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
  AuthenticatedTransportersIndexRoute: AuthenticatedTransportersIndexRoute,
  AuthenticatedTrucksIndexRoute: AuthenticatedTrucksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
