/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnomaliesRouteImport } from './routes/_authenticated/anomalies'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertRulesIndexRouteImport } from './routes/_authenticated/alert-rules/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedAnomaliesIndexRouteImport } from './routes/_authenticated/anomalies/index'
import { Route as AuthenticatedAnomaliesInvestigationRouteImport } from './routes/_authenticated/anomalies/investigation'
import { Route as AuthenticatedAnomaliesTechnicalRouteImport } from './routes/_authenticated/anomalies/technical'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedCertificatesIndexRouteImport } from './routes/_authenticated/certificates/index'
import { Route as AuthenticatedClientSitesIndexRouteImport } from './routes/_authenticated/client-sites/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedCustomRolesIndexRouteImport } from './routes/_authenticated/custom-roles/index'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard-admin/index'
import { Route as AuthenticatedDashboardMarketeurIndexRouteImport } from './routes/_authenticated/dashboard-marketeur/index'
import { Route as AuthenticatedDashboardSupervisorIndexRouteImport } from './routes/_authenticated/dashboard-supervisor/index'
import { Route as AuthenticatedDashboardTransporteurIndexRouteImport } from './routes/_authenticated/dashboard-transporteur/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDeclarationsIndexRouteImport } from './routes/_authenticated/declarations/index'
import { Route as AuthenticatedDepotsIndexRouteImport } from './routes/_authenticated/depots/index'
import { Route as AuthenticatedDeviceAssignmentsIndexRouteImport } from './routes/_authenticated/device-assignments/index'
import { Route as AuthenticatedDeviceHealthIndexRouteImport } from './routes/_authenticated/device-health/index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices/index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedFirmwareIndexRouteImport } from './routes/_authenticated/firmware/index'
import { Route as AuthenticatedGpsConfigIndexRouteImport } from './routes/_authenticated/gps-config/index'
import { Route as AuthenticatedGpsTrackingIndexRouteImport } from './routes/_authenticated/gps-tracking/index'
import { Route as AuthenticatedInfraIndexRouteImport } from './routes/_authenticated/infra/index'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations/index'
import { Route as AuthenticatedLivreursIndexRouteImport } from './routes/_authenticated/livreurs/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance/index'
import { Route as AuthenticatedMapIndexRouteImport } from './routes/_authenticated/map/index'
import { Route as AuthenticatedMarketersIndexRouteImport } from './routes/_authenticated/marketers/index'
import { Route as AuthenticatedMarketersMarketerIdRouteImport } from './routes/_authenticated/marketers/$marketerId'
import { Route as AuthenticatedNotificationGroupsIndexRouteImport } from './routes/_authenticated/notification-groups/index'
import { Route as AuthenticatedNotificationRulesIndexRouteImport } from './routes/_authenticated/notification-rules/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedPasswordsIndexRouteImport } from './routes/_authenticated/passwords/index'
import { Route as AuthenticatedPerformanceIndexRouteImport } from './routes/_authenticated/performance/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedPickupTrackingIndexRouteImport } from './routes/_authenticated/pickup-tracking/index'
import { Route as AuthenticatedPickupsIndexRouteImport } from './routes/_authenticated/pickups/index'
import { Route as AuthenticatedQuotasIndexRouteImport } from './routes/_authenticated/quotas/index'
import { Route as AuthenticatedRecomputeIndexRouteImport } from './routes/_authenticated/recompute/index'
import { Route as AuthenticatedReconciliationsIndexRouteImport } from './routes/_authenticated/reconciliations/index'
import { Route as AuthenticatedRedressementsIndexRouteImport } from './routes/_authenticated/redressements/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedRfidTagsIndexRouteImport } from './routes/_authenticated/rfid-tags/index'
import { Route as AuthenticatedRiskScoresIndexRouteImport } from './routes/_authenticated/risk-scores/index'
import { Route as AuthenticatedRisksIndexRouteImport } from './routes/_authenticated/risks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsNotificationGroupsRouteImport } from './routes/_authenticated/settings/notification-groups'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSiteVerificationsIndexRouteImport } from './routes/_authenticated/site-verifications/index'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites/index'
import { Route as AuthenticatedSupplyIndexRouteImport } from './routes/_authenticated/supply/index'
import { Route as AuthenticatedSystemHealthIndexRouteImport } from './routes/_authenticated/system-health/index'
import { Route as AuthenticatedSystemMetricsIndexRouteImport } from './routes/_authenticated/system-metrics/index'
import { Route as AuthenticatedTourTrackingIndexRouteImport } from './routes/_authenticated/tour-tracking/index'
import { Route as AuthenticatedTourTrackingTourIdRouteImport } from './routes/_authenticated/tour-tracking/$tourId'
import { Route as AuthenticatedToursIndexRouteImport } from './routes/_authenticated/tours/index'
import { Route as AuthenticatedTransporterContractsIndexRouteImport } from './routes/_authenticated/transporter-contracts/index'
import { Route as AuthenticatedTransportersIndexRouteImport } from './routes/_authenticated/transporters/index'
import { Route as AuthenticatedTransportersTransporterIdRouteImport } from './routes/_authenticated/transporters/$transporterId'
import { Route as AuthenticatedTrucksIndexRouteImport } from './routes/_authenticated/trucks/index'
import { Route as AuthenticatedTrucksTruckIdRouteImport } from './routes/_authenticated/trucks/$truckId'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles/index'
import { Route as AuthenticatedVisitsIndexRouteImport } from './routes/_authenticated/visits/index'
import { Route as AuthenticatedZonesIndexRouteImport } from './routes/_authenticated/zones/index'
import { Route as AuthenticatedDashboardFleetsFleetNameRouteImport } from './routes/_authenticated/dashboard/fleets/$fleetName'
import { Route as AuthenticatedDashboardSitesSiteIdRouteImport } from './routes/_authenticated/dashboard/sites/$siteId'
import { Route as AuthenticatedSuperAdminToursIndexRouteImport } from './routes/_authenticated/super-admin/tours/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnomaliesRoute = AuthenticatedAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertRulesIndexRoute =
  AuthenticatedAlertRulesIndexRouteImport.update({
    id: '/alert-rules/',
    path: '/alert-rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnomaliesIndexRoute =
  AuthenticatedAnomaliesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnomaliesRoute,
  } as any)
const AuthenticatedAnomaliesInvestigationRoute =
  AuthenticatedAnomaliesInvestigationRouteImport.update({
    id: '/investigation',
    path: '/investigation',
    getParentRoute: () => AuthenticatedAnomaliesRoute,
  } as any)
const AuthenticatedAnomaliesTechnicalRoute =
  AuthenticatedAnomaliesTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => AuthenticatedAnomaliesRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificatesIndexRoute =
  AuthenticatedCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientSitesIndexRoute =
  AuthenticatedClientSitesIndexRouteImport.update({
    id: '/client-sites/',
    path: '/client-sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomRolesIndexRoute =
  AuthenticatedCustomRolesIndexRouteImport.update({
    id: '/custom-roles/',
    path: '/custom-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/dashboard-admin/',
    path: '/dashboard-admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMarketeurIndexRoute =
  AuthenticatedDashboardMarketeurIndexRouteImport.update({
    id: '/dashboard-marketeur/',
    path: '/dashboard-marketeur/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSupervisorIndexRoute =
  AuthenticatedDashboardSupervisorIndexRouteImport.update({
    id: '/dashboard-supervisor/',
    path: '/dashboard-supervisor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTransporteurIndexRoute =
  AuthenticatedDashboardTransporteurIndexRouteImport.update({
    id: '/dashboard-transporteur/',
    path: '/dashboard-transporteur/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDeclarationsIndexRoute =
  AuthenticatedDeclarationsIndexRouteImport.update({
    id: '/declarations/',
    path: '/declarations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepotsIndexRoute =
  AuthenticatedDepotsIndexRouteImport.update({
    id: '/depots/',
    path: '/depots/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceAssignmentsIndexRoute =
  AuthenticatedDeviceAssignmentsIndexRouteImport.update({
    id: '/device-assignments/',
    path: '/device-assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceHealthIndexRoute =
  AuthenticatedDeviceHealthIndexRouteImport.update({
    id: '/device-health/',
    path: '/device-health/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFirmwareIndexRoute =
  AuthenticatedFirmwareIndexRouteImport.update({
    id: '/firmware/',
    path: '/firmware/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGpsConfigIndexRoute =
  AuthenticatedGpsConfigIndexRouteImport.update({
    id: '/gps-config/',
    path: '/gps-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGpsTrackingIndexRoute =
  AuthenticatedGpsTrackingIndexRouteImport.update({
    id: '/gps-tracking/',
    path: '/gps-tracking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfraIndexRoute = AuthenticatedInfraIndexRouteImport.update({
  id: '/infra/',
  path: '/infra/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLivreursIndexRoute =
  AuthenticatedLivreursIndexRouteImport.update({
    id: '/livreurs/',
    path: '/livreurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapIndexRoute = AuthenticatedMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketersIndexRoute =
  AuthenticatedMarketersIndexRouteImport.update({
    id: '/marketers/',
    path: '/marketers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketersMarketerIdRoute =
  AuthenticatedMarketersMarketerIdRouteImport.update({
    id: '/marketers/$marketerId',
    path: '/marketers/$marketerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationGroupsIndexRoute =
  AuthenticatedNotificationGroupsIndexRouteImport.update({
    id: '/notification-groups/',
    path: '/notification-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationRulesIndexRoute =
  AuthenticatedNotificationRulesIndexRouteImport.update({
    id: '/notification-rules/',
    path: '/notification-rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPasswordsIndexRoute =
  AuthenticatedPasswordsIndexRouteImport.update({
    id: '/passwords/',
    path: '/passwords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceIndexRoute =
  AuthenticatedPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPickupTrackingIndexRoute =
  AuthenticatedPickupTrackingIndexRouteImport.update({
    id: '/pickup-tracking/',
    path: '/pickup-tracking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPickupsIndexRoute =
  AuthenticatedPickupsIndexRouteImport.update({
    id: '/pickups/',
    path: '/pickups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotasIndexRoute =
  AuthenticatedQuotasIndexRouteImport.update({
    id: '/quotas/',
    path: '/quotas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecomputeIndexRoute =
  AuthenticatedRecomputeIndexRouteImport.update({
    id: '/recompute/',
    path: '/recompute/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReconciliationsIndexRoute =
  AuthenticatedReconciliationsIndexRouteImport.update({
    id: '/reconciliations/',
    path: '/reconciliations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedressementsIndexRoute =
  AuthenticatedRedressementsIndexRouteImport.update({
    id: '/redressements/',
    path: '/redressements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfidTagsIndexRoute =
  AuthenticatedRfidTagsIndexRouteImport.update({
    id: '/rfid-tags/',
    path: '/rfid-tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiskScoresIndexRoute =
  AuthenticatedRiskScoresIndexRouteImport.update({
    id: '/risk-scores/',
    path: '/risk-scores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRisksIndexRoute = AuthenticatedRisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationGroupsRoute =
  AuthenticatedSettingsNotificationGroupsRouteImport.update({
    id: '/settings/notification-groups',
    path: '/settings/notification-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteVerificationsIndexRoute =
  AuthenticatedSiteVerificationsIndexRouteImport.update({
    id: '/site-verifications/',
    path: '/site-verifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplyIndexRoute =
  AuthenticatedSupplyIndexRouteImport.update({
    id: '/supply/',
    path: '/supply/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemHealthIndexRoute =
  AuthenticatedSystemHealthIndexRouteImport.update({
    id: '/system-health/',
    path: '/system-health/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemMetricsIndexRoute =
  AuthenticatedSystemMetricsIndexRouteImport.update({
    id: '/system-metrics/',
    path: '/system-metrics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourTrackingIndexRoute =
  AuthenticatedTourTrackingIndexRouteImport.update({
    id: '/tour-tracking/',
    path: '/tour-tracking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourTrackingTourIdRoute =
  AuthenticatedTourTrackingTourIdRouteImport.update({
    id: '/tour-tracking/$tourId',
    path: '/tour-tracking/$tourId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToursIndexRoute = AuthenticatedToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransporterContractsIndexRoute =
  AuthenticatedTransporterContractsIndexRouteImport.update({
    id: '/transporter-contracts/',
    path: '/transporter-contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportersIndexRoute =
  AuthenticatedTransportersIndexRouteImport.update({
    id: '/transporters/',
    path: '/transporters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportersTransporterIdRoute =
  AuthenticatedTransportersTransporterIdRouteImport.update({
    id: '/transporters/$transporterId',
    path: '/transporters/$transporterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrucksIndexRoute =
  AuthenticatedTrucksIndexRouteImport.update({
    id: '/trucks/',
    path: '/trucks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrucksTruckIdRoute =
  AuthenticatedTrucksTruckIdRouteImport.update({
    id: '/trucks/$truckId',
    path: '/trucks/$truckId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitsIndexRoute =
  AuthenticatedVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZonesIndexRoute = AuthenticatedZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardFleetsFleetNameRoute =
  AuthenticatedDashboardFleetsFleetNameRouteImport.update({
    id: '/fleets/$fleetName',
    path: '/fleets/$fleetName',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSitesSiteIdRoute =
  AuthenticatedDashboardSitesSiteIdRouteImport.update({
    id: '/sites/$siteId',
    path: '/sites/$siteId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSuperAdminToursIndexRoute =
  AuthenticatedSuperAdminToursIndexRouteImport.update({
    id: '/super-admin/tours/',
    path: '/super-admin/tours/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/anomalies': typeof AuthenticatedAnomaliesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/anomalies/investigation': typeof AuthenticatedAnomaliesInvestigationRoute
  '/anomalies/technical': typeof AuthenticatedAnomaliesTechnicalRoute
  '/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/settings/notification-groups': typeof AuthenticatedSettingsNotificationGroupsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/tour-tracking/$tourId': typeof AuthenticatedTourTrackingTourIdRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/trucks/$truckId': typeof AuthenticatedTrucksTruckIdRoute
  '/alert-rules/': typeof AuthenticatedAlertRulesIndexRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/anomalies/': typeof AuthenticatedAnomaliesIndexRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/client-sites/': typeof AuthenticatedClientSitesIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/custom-roles/': typeof AuthenticatedCustomRolesIndexRoute
  '/dashboard-admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard-marketeur/': typeof AuthenticatedDashboardMarketeurIndexRoute
  '/dashboard-supervisor/': typeof AuthenticatedDashboardSupervisorIndexRoute
  '/dashboard-transporteur/': typeof AuthenticatedDashboardTransporteurIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/declarations/': typeof AuthenticatedDeclarationsIndexRoute
  '/depots/': typeof AuthenticatedDepotsIndexRoute
  '/device-assignments/': typeof AuthenticatedDeviceAssignmentsIndexRoute
  '/device-health/': typeof AuthenticatedDeviceHealthIndexRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/firmware/': typeof AuthenticatedFirmwareIndexRoute
  '/gps-config/': typeof AuthenticatedGpsConfigIndexRoute
  '/gps-tracking/': typeof AuthenticatedGpsTrackingIndexRoute
  '/infra/': typeof AuthenticatedInfraIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/livreurs/': typeof AuthenticatedLivreursIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/map/': typeof AuthenticatedMapIndexRoute
  '/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/notification-groups/': typeof AuthenticatedNotificationGroupsIndexRoute
  '/notification-rules/': typeof AuthenticatedNotificationRulesIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
  '/passwords/': typeof AuthenticatedPasswordsIndexRoute
  '/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/pickup-tracking/': typeof AuthenticatedPickupTrackingIndexRoute
  '/pickups/': typeof AuthenticatedPickupsIndexRoute
  '/quotas/': typeof AuthenticatedQuotasIndexRoute
  '/recompute/': typeof AuthenticatedRecomputeIndexRoute
  '/reconciliations/': typeof AuthenticatedReconciliationsIndexRoute
  '/redressements/': typeof AuthenticatedRedressementsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/rfid-tags/': typeof AuthenticatedRfidTagsIndexRoute
  '/risk-scores/': typeof AuthenticatedRiskScoresIndexRoute
  '/risks/': typeof AuthenticatedRisksIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/site-verifications/': typeof AuthenticatedSiteVerificationsIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/supply/': typeof AuthenticatedSupplyIndexRoute
  '/system-health/': typeof AuthenticatedSystemHealthIndexRoute
  '/system-metrics/': typeof AuthenticatedSystemMetricsIndexRoute
  '/tour-tracking/': typeof AuthenticatedTourTrackingIndexRoute
  '/tours/': typeof AuthenticatedToursIndexRoute
  '/transporter-contracts/': typeof AuthenticatedTransporterContractsIndexRoute
  '/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/trucks/': typeof AuthenticatedTrucksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/visits/': typeof AuthenticatedVisitsIndexRoute
  '/zones/': typeof AuthenticatedZonesIndexRoute
  '/dashboard/fleets/$fleetName': typeof AuthenticatedDashboardFleetsFleetNameRoute
  '/dashboard/sites/$siteId': typeof AuthenticatedDashboardSitesSiteIdRoute
  '/super-admin/tours/': typeof AuthenticatedSuperAdminToursIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/': typeof AuthenticatedIndexRoute
  '/anomalies/investigation': typeof AuthenticatedAnomaliesInvestigationRoute
  '/anomalies/technical': typeof AuthenticatedAnomaliesTechnicalRoute
  '/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/settings/notification-groups': typeof AuthenticatedSettingsNotificationGroupsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/tour-tracking/$tourId': typeof AuthenticatedTourTrackingTourIdRoute
  '/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/trucks/$truckId': typeof AuthenticatedTrucksTruckIdRoute
  '/alert-rules': typeof AuthenticatedAlertRulesIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/anomalies': typeof AuthenticatedAnomaliesIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/certificates': typeof AuthenticatedCertificatesIndexRoute
  '/client-sites': typeof AuthenticatedClientSitesIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/custom-roles': typeof AuthenticatedCustomRolesIndexRoute
  '/dashboard-admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard-marketeur': typeof AuthenticatedDashboardMarketeurIndexRoute
  '/dashboard-supervisor': typeof AuthenticatedDashboardSupervisorIndexRoute
  '/dashboard-transporteur': typeof AuthenticatedDashboardTransporteurIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/declarations': typeof AuthenticatedDeclarationsIndexRoute
  '/depots': typeof AuthenticatedDepotsIndexRoute
  '/device-assignments': typeof AuthenticatedDeviceAssignmentsIndexRoute
  '/device-health': typeof AuthenticatedDeviceHealthIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/firmware': typeof AuthenticatedFirmwareIndexRoute
  '/gps-config': typeof AuthenticatedGpsConfigIndexRoute
  '/gps-tracking': typeof AuthenticatedGpsTrackingIndexRoute
  '/infra': typeof AuthenticatedInfraIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/livreurs': typeof AuthenticatedLivreursIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/map': typeof AuthenticatedMapIndexRoute
  '/marketers': typeof AuthenticatedMarketersIndexRoute
  '/notification-groups': typeof AuthenticatedNotificationGroupsIndexRoute
  '/notification-rules': typeof AuthenticatedNotificationRulesIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
  '/passwords': typeof AuthenticatedPasswordsIndexRoute
  '/performance': typeof AuthenticatedPerformanceIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/pickup-tracking': typeof AuthenticatedPickupTrackingIndexRoute
  '/pickups': typeof AuthenticatedPickupsIndexRoute
  '/quotas': typeof AuthenticatedQuotasIndexRoute
  '/recompute': typeof AuthenticatedRecomputeIndexRoute
  '/reconciliations': typeof AuthenticatedReconciliationsIndexRoute
  '/redressements': typeof AuthenticatedRedressementsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/rfid-tags': typeof AuthenticatedRfidTagsIndexRoute
  '/risk-scores': typeof AuthenticatedRiskScoresIndexRoute
  '/risks': typeof AuthenticatedRisksIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/site-verifications': typeof AuthenticatedSiteVerificationsIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/supply': typeof AuthenticatedSupplyIndexRoute
  '/system-health': typeof AuthenticatedSystemHealthIndexRoute
  '/system-metrics': typeof AuthenticatedSystemMetricsIndexRoute
  '/tour-tracking': typeof AuthenticatedTourTrackingIndexRoute
  '/tours': typeof AuthenticatedToursIndexRoute
  '/transporter-contracts': typeof AuthenticatedTransporterContractsIndexRoute
  '/transporters': typeof AuthenticatedTransportersIndexRoute
  '/trucks': typeof AuthenticatedTrucksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
  '/visits': typeof AuthenticatedVisitsIndexRoute
  '/zones': typeof AuthenticatedZonesIndexRoute
  '/dashboard/fleets/$fleetName': typeof AuthenticatedDashboardFleetsFleetNameRoute
  '/dashboard/sites/$siteId': typeof AuthenticatedDashboardSitesSiteIdRoute
  '/super-admin/tours': typeof AuthenticatedSuperAdminToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/_authenticated/anomalies': typeof AuthenticatedAnomaliesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/anomalies/investigation': typeof AuthenticatedAnomaliesInvestigationRoute
  '/_authenticated/anomalies/technical': typeof AuthenticatedAnomaliesTechnicalRoute
  '/_authenticated/marketers/$marketerId': typeof AuthenticatedMarketersMarketerIdRoute
  '/_authenticated/settings/notification-groups': typeof AuthenticatedSettingsNotificationGroupsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/tour-tracking/$tourId': typeof AuthenticatedTourTrackingTourIdRoute
  '/_authenticated/transporters/$transporterId': typeof AuthenticatedTransportersTransporterIdRoute
  '/_authenticated/trucks/$truckId': typeof AuthenticatedTrucksTruckIdRoute
  '/_authenticated/alert-rules/': typeof AuthenticatedAlertRulesIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/anomalies/': typeof AuthenticatedAnomaliesIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/_authenticated/client-sites/': typeof AuthenticatedClientSitesIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/custom-roles/': typeof AuthenticatedCustomRolesIndexRoute
  '/_authenticated/dashboard-admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard-marketeur/': typeof AuthenticatedDashboardMarketeurIndexRoute
  '/_authenticated/dashboard-supervisor/': typeof AuthenticatedDashboardSupervisorIndexRoute
  '/_authenticated/dashboard-transporteur/': typeof AuthenticatedDashboardTransporteurIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/declarations/': typeof AuthenticatedDeclarationsIndexRoute
  '/_authenticated/depots/': typeof AuthenticatedDepotsIndexRoute
  '/_authenticated/device-assignments/': typeof AuthenticatedDeviceAssignmentsIndexRoute
  '/_authenticated/device-health/': typeof AuthenticatedDeviceHealthIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/firmware/': typeof AuthenticatedFirmwareIndexRoute
  '/_authenticated/gps-config/': typeof AuthenticatedGpsConfigIndexRoute
  '/_authenticated/gps-tracking/': typeof AuthenticatedGpsTrackingIndexRoute
  '/_authenticated/infra/': typeof AuthenticatedInfraIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/livreurs/': typeof AuthenticatedLivreursIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/map/': typeof AuthenticatedMapIndexRoute
  '/_authenticated/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/_authenticated/notification-groups/': typeof AuthenticatedNotificationGroupsIndexRoute
  '/_authenticated/notification-rules/': typeof AuthenticatedNotificationRulesIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/_authenticated/passwords/': typeof AuthenticatedPasswordsIndexRoute
  '/_authenticated/performance/': typeof AuthenticatedPerformanceIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/pickup-tracking/': typeof AuthenticatedPickupTrackingIndexRoute
  '/_authenticated/pickups/': typeof AuthenticatedPickupsIndexRoute
  '/_authenticated/quotas/': typeof AuthenticatedQuotasIndexRoute
  '/_authenticated/recompute/': typeof AuthenticatedRecomputeIndexRoute
  '/_authenticated/reconciliations/': typeof AuthenticatedReconciliationsIndexRoute
  '/_authenticated/redressements/': typeof AuthenticatedRedressementsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/rfid-tags/': typeof AuthenticatedRfidTagsIndexRoute
  '/_authenticated/risk-scores/': typeof AuthenticatedRiskScoresIndexRoute
  '/_authenticated/risks/': typeof AuthenticatedRisksIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/site-verifications/': typeof AuthenticatedSiteVerificationsIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/supply/': typeof AuthenticatedSupplyIndexRoute
  '/_authenticated/system-health/': typeof AuthenticatedSystemHealthIndexRoute
  '/_authenticated/system-metrics/': typeof AuthenticatedSystemMetricsIndexRoute
  '/_authenticated/tour-tracking/': typeof AuthenticatedTourTrackingIndexRoute
  '/_authenticated/tours/': typeof AuthenticatedToursIndexRoute
  '/_authenticated/transporter-contracts/': typeof AuthenticatedTransporterContractsIndexRoute
  '/_authenticated/transporters/': typeof AuthenticatedTransportersIndexRoute
  '/_authenticated/trucks/': typeof AuthenticatedTrucksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/_authenticated/visits/': typeof AuthenticatedVisitsIndexRoute
  '/_authenticated/zones/': typeof AuthenticatedZonesIndexRoute
  '/_authenticated/dashboard/fleets/$fleetName': typeof AuthenticatedDashboardFleetsFleetNameRoute
  '/_authenticated/dashboard/sites/$siteId': typeof AuthenticatedDashboardSitesSiteIdRoute
  '/_authenticated/super-admin/tours/': typeof AuthenticatedSuperAdminToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/terms'
    | '/anomalies'
    | '/dashboard'
    | '/anomalies/investigation'
    | '/anomalies/technical'
    | '/marketers/$marketerId'
    | '/settings/notification-groups'
    | '/settings/profile'
    | '/settings/system'
    | '/tour-tracking/$tourId'
    | '/transporters/$transporterId'
    | '/trucks/$truckId'
    | '/alert-rules/'
    | '/alerts/'
    | '/anomalies/'
    | '/audit-logs/'
    | '/certificates/'
    | '/client-sites/'
    | '/clients/'
    | '/contracts/'
    | '/custom-roles/'
    | '/dashboard-admin/'
    | '/dashboard-marketeur/'
    | '/dashboard-supervisor/'
    | '/dashboard-transporteur/'
    | '/dashboard/'
    | '/declarations/'
    | '/depots/'
    | '/device-assignments/'
    | '/device-health/'
    | '/devices/'
    | '/drivers/'
    | '/finance/'
    | '/firmware/'
    | '/gps-config/'
    | '/gps-tracking/'
    | '/infra/'
    | '/integrations/'
    | '/livreurs/'
    | '/logs/'
    | '/maintenance/'
    | '/map/'
    | '/marketers/'
    | '/notification-groups/'
    | '/notification-rules/'
    | '/organizations/'
    | '/overview/'
    | '/passwords/'
    | '/performance/'
    | '/permissions/'
    | '/pickup-tracking/'
    | '/pickups/'
    | '/quotas/'
    | '/recompute/'
    | '/reconciliations/'
    | '/redressements/'
    | '/reports/'
    | '/rfid-tags/'
    | '/risk-scores/'
    | '/risks/'
    | '/settings/'
    | '/site-verifications/'
    | '/sites/'
    | '/supply/'
    | '/system-health/'
    | '/system-metrics/'
    | '/tour-tracking/'
    | '/tours/'
    | '/transporter-contracts/'
    | '/transporters/'
    | '/trucks/'
    | '/users/'
    | '/vehicles/'
    | '/visits/'
    | '/zones/'
    | '/dashboard/fleets/$fleetName'
    | '/dashboard/sites/$siteId'
    | '/super-admin/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/terms'
    | '/'
    | '/anomalies/investigation'
    | '/anomalies/technical'
    | '/marketers/$marketerId'
    | '/settings/notification-groups'
    | '/settings/profile'
    | '/settings/system'
    | '/tour-tracking/$tourId'
    | '/transporters/$transporterId'
    | '/trucks/$truckId'
    | '/alert-rules'
    | '/alerts'
    | '/anomalies'
    | '/audit-logs'
    | '/certificates'
    | '/client-sites'
    | '/clients'
    | '/contracts'
    | '/custom-roles'
    | '/dashboard-admin'
    | '/dashboard-marketeur'
    | '/dashboard-supervisor'
    | '/dashboard-transporteur'
    | '/dashboard'
    | '/declarations'
    | '/depots'
    | '/device-assignments'
    | '/device-health'
    | '/devices'
    | '/drivers'
    | '/finance'
    | '/firmware'
    | '/gps-config'
    | '/gps-tracking'
    | '/infra'
    | '/integrations'
    | '/livreurs'
    | '/logs'
    | '/maintenance'
    | '/map'
    | '/marketers'
    | '/notification-groups'
    | '/notification-rules'
    | '/organizations'
    | '/overview'
    | '/passwords'
    | '/performance'
    | '/permissions'
    | '/pickup-tracking'
    | '/pickups'
    | '/quotas'
    | '/recompute'
    | '/reconciliations'
    | '/redressements'
    | '/reports'
    | '/rfid-tags'
    | '/risk-scores'
    | '/risks'
    | '/settings'
    | '/site-verifications'
    | '/sites'
    | '/supply'
    | '/system-health'
    | '/system-metrics'
    | '/tour-tracking'
    | '/tours'
    | '/transporter-contracts'
    | '/transporters'
    | '/trucks'
    | '/users'
    | '/vehicles'
    | '/visits'
    | '/zones'
    | '/dashboard/fleets/$fleetName'
    | '/dashboard/sites/$siteId'
    | '/super-admin/tours'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/terms'
    | '/_authenticated/anomalies'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/anomalies/investigation'
    | '/_authenticated/anomalies/technical'
    | '/_authenticated/marketers/$marketerId'
    | '/_authenticated/settings/notification-groups'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/system'
    | '/_authenticated/tour-tracking/$tourId'
    | '/_authenticated/transporters/$transporterId'
    | '/_authenticated/trucks/$truckId'
    | '/_authenticated/alert-rules/'
    | '/_authenticated/alerts/'
    | '/_authenticated/anomalies/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/certificates/'
    | '/_authenticated/client-sites/'
    | '/_authenticated/clients/'
    | '/_authenticated/contracts/'
    | '/_authenticated/custom-roles/'
    | '/_authenticated/dashboard-admin/'
    | '/_authenticated/dashboard-marketeur/'
    | '/_authenticated/dashboard-supervisor/'
    | '/_authenticated/dashboard-transporteur/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/declarations/'
    | '/_authenticated/depots/'
    | '/_authenticated/device-assignments/'
    | '/_authenticated/device-health/'
    | '/_authenticated/devices/'
    | '/_authenticated/drivers/'
    | '/_authenticated/finance/'
    | '/_authenticated/firmware/'
    | '/_authenticated/gps-config/'
    | '/_authenticated/gps-tracking/'
    | '/_authenticated/infra/'
    | '/_authenticated/integrations/'
    | '/_authenticated/livreurs/'
    | '/_authenticated/logs/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/map/'
    | '/_authenticated/marketers/'
    | '/_authenticated/notification-groups/'
    | '/_authenticated/notification-rules/'
    | '/_authenticated/organizations/'
    | '/_authenticated/overview/'
    | '/_authenticated/passwords/'
    | '/_authenticated/performance/'
    | '/_authenticated/permissions/'
    | '/_authenticated/pickup-tracking/'
    | '/_authenticated/pickups/'
    | '/_authenticated/quotas/'
    | '/_authenticated/recompute/'
    | '/_authenticated/reconciliations/'
    | '/_authenticated/redressements/'
    | '/_authenticated/reports/'
    | '/_authenticated/rfid-tags/'
    | '/_authenticated/risk-scores/'
    | '/_authenticated/risks/'
    | '/_authenticated/settings/'
    | '/_authenticated/site-verifications/'
    | '/_authenticated/sites/'
    | '/_authenticated/supply/'
    | '/_authenticated/system-health/'
    | '/_authenticated/system-metrics/'
    | '/_authenticated/tour-tracking/'
    | '/_authenticated/tours/'
    | '/_authenticated/transporter-contracts/'
    | '/_authenticated/transporters/'
    | '/_authenticated/trucks/'
    | '/_authenticated/users/'
    | '/_authenticated/vehicles/'
    | '/_authenticated/visits/'
    | '/_authenticated/zones/'
    | '/_authenticated/dashboard/fleets/$fleetName'
    | '/_authenticated/dashboard/sites/$siteId'
    | '/_authenticated/super-admin/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anomalies': {
      id: '/_authenticated/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AuthenticatedAnomaliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alert-rules/': {
      id: '/_authenticated/alert-rules/'
      path: '/alert-rules'
      fullPath: '/alert-rules/'
      preLoaderRoute: typeof AuthenticatedAlertRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anomalies/': {
      id: '/_authenticated/anomalies/'
      path: '/'
      fullPath: '/anomalies/'
      preLoaderRoute: typeof AuthenticatedAnomaliesIndexRouteImport
      parentRoute: typeof AuthenticatedAnomaliesRoute
    }
    '/_authenticated/anomalies/investigation': {
      id: '/_authenticated/anomalies/investigation'
      path: '/investigation'
      fullPath: '/anomalies/investigation'
      preLoaderRoute: typeof AuthenticatedAnomaliesInvestigationRouteImport
      parentRoute: typeof AuthenticatedAnomaliesRoute
    }
    '/_authenticated/anomalies/technical': {
      id: '/_authenticated/anomalies/technical'
      path: '/technical'
      fullPath: '/anomalies/technical'
      preLoaderRoute: typeof AuthenticatedAnomaliesTechnicalRouteImport
      parentRoute: typeof AuthenticatedAnomaliesRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates/': {
      id: '/_authenticated/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthenticatedCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-sites/': {
      id: '/_authenticated/client-sites/'
      path: '/client-sites'
      fullPath: '/client-sites/'
      preLoaderRoute: typeof AuthenticatedClientSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custom-roles/': {
      id: '/_authenticated/custom-roles/'
      path: '/custom-roles'
      fullPath: '/custom-roles/'
      preLoaderRoute: typeof AuthenticatedCustomRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-admin/': {
      id: '/_authenticated/dashboard-admin/'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-marketeur/': {
      id: '/_authenticated/dashboard-marketeur/'
      path: '/dashboard-marketeur'
      fullPath: '/dashboard-marketeur/'
      preLoaderRoute: typeof AuthenticatedDashboardMarketeurIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-supervisor/': {
      id: '/_authenticated/dashboard-supervisor/'
      path: '/dashboard-supervisor'
      fullPath: '/dashboard-supervisor/'
      preLoaderRoute: typeof AuthenticatedDashboardSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-transporteur/': {
      id: '/_authenticated/dashboard-transporteur/'
      path: '/dashboard-transporteur'
      fullPath: '/dashboard-transporteur/'
      preLoaderRoute: typeof AuthenticatedDashboardTransporteurIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/declarations/': {
      id: '/_authenticated/declarations/'
      path: '/declarations'
      fullPath: '/declarations/'
      preLoaderRoute: typeof AuthenticatedDeclarationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depots/': {
      id: '/_authenticated/depots/'
      path: '/depots'
      fullPath: '/depots/'
      preLoaderRoute: typeof AuthenticatedDepotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-assignments/': {
      id: '/_authenticated/device-assignments/'
      path: '/device-assignments'
      fullPath: '/device-assignments/'
      preLoaderRoute: typeof AuthenticatedDeviceAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-health/': {
      id: '/_authenticated/device-health/'
      path: '/device-health'
      fullPath: '/device-health/'
      preLoaderRoute: typeof AuthenticatedDeviceHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/firmware/': {
      id: '/_authenticated/firmware/'
      path: '/firmware'
      fullPath: '/firmware/'
      preLoaderRoute: typeof AuthenticatedFirmwareIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gps-config/': {
      id: '/_authenticated/gps-config/'
      path: '/gps-config'
      fullPath: '/gps-config/'
      preLoaderRoute: typeof AuthenticatedGpsConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gps-tracking/': {
      id: '/_authenticated/gps-tracking/'
      path: '/gps-tracking'
      fullPath: '/gps-tracking/'
      preLoaderRoute: typeof AuthenticatedGpsTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infra/': {
      id: '/_authenticated/infra/'
      path: '/infra'
      fullPath: '/infra/'
      preLoaderRoute: typeof AuthenticatedInfraIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreurs/': {
      id: '/_authenticated/livreurs/'
      path: '/livreurs'
      fullPath: '/livreurs/'
      preLoaderRoute: typeof AuthenticatedLivreursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map/': {
      id: '/_authenticated/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof AuthenticatedMapIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketers/': {
      id: '/_authenticated/marketers/'
      path: '/marketers'
      fullPath: '/marketers/'
      preLoaderRoute: typeof AuthenticatedMarketersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketers/$marketerId': {
      id: '/_authenticated/marketers/$marketerId'
      path: '/marketers/$marketerId'
      fullPath: '/marketers/$marketerId'
      preLoaderRoute: typeof AuthenticatedMarketersMarketerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-groups/': {
      id: '/_authenticated/notification-groups/'
      path: '/notification-groups'
      fullPath: '/notification-groups/'
      preLoaderRoute: typeof AuthenticatedNotificationGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-rules/': {
      id: '/_authenticated/notification-rules/'
      path: '/notification-rules'
      fullPath: '/notification-rules/'
      preLoaderRoute: typeof AuthenticatedNotificationRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passwords/': {
      id: '/_authenticated/passwords/'
      path: '/passwords'
      fullPath: '/passwords/'
      preLoaderRoute: typeof AuthenticatedPasswordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance/': {
      id: '/_authenticated/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof AuthenticatedPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pickup-tracking/': {
      id: '/_authenticated/pickup-tracking/'
      path: '/pickup-tracking'
      fullPath: '/pickup-tracking/'
      preLoaderRoute: typeof AuthenticatedPickupTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pickups/': {
      id: '/_authenticated/pickups/'
      path: '/pickups'
      fullPath: '/pickups/'
      preLoaderRoute: typeof AuthenticatedPickupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotas/': {
      id: '/_authenticated/quotas/'
      path: '/quotas'
      fullPath: '/quotas/'
      preLoaderRoute: typeof AuthenticatedQuotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompute/': {
      id: '/_authenticated/recompute/'
      path: '/recompute'
      fullPath: '/recompute/'
      preLoaderRoute: typeof AuthenticatedRecomputeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliations/': {
      id: '/_authenticated/reconciliations/'
      path: '/reconciliations'
      fullPath: '/reconciliations/'
      preLoaderRoute: typeof AuthenticatedReconciliationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redressements/': {
      id: '/_authenticated/redressements/'
      path: '/redressements'
      fullPath: '/redressements/'
      preLoaderRoute: typeof AuthenticatedRedressementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfid-tags/': {
      id: '/_authenticated/rfid-tags/'
      path: '/rfid-tags'
      fullPath: '/rfid-tags/'
      preLoaderRoute: typeof AuthenticatedRfidTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk-scores/': {
      id: '/_authenticated/risk-scores/'
      path: '/risk-scores'
      fullPath: '/risk-scores/'
      preLoaderRoute: typeof AuthenticatedRiskScoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risks/': {
      id: '/_authenticated/risks/'
      path: '/risks'
      fullPath: '/risks/'
      preLoaderRoute: typeof AuthenticatedRisksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notification-groups': {
      id: '/_authenticated/settings/notification-groups'
      path: '/settings/notification-groups'
      fullPath: '/settings/notification-groups'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-verifications/': {
      id: '/_authenticated/site-verifications/'
      path: '/site-verifications'
      fullPath: '/site-verifications/'
      preLoaderRoute: typeof AuthenticatedSiteVerificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply/': {
      id: '/_authenticated/supply/'
      path: '/supply'
      fullPath: '/supply/'
      preLoaderRoute: typeof AuthenticatedSupplyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-health/': {
      id: '/_authenticated/system-health/'
      path: '/system-health'
      fullPath: '/system-health/'
      preLoaderRoute: typeof AuthenticatedSystemHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-metrics/': {
      id: '/_authenticated/system-metrics/'
      path: '/system-metrics'
      fullPath: '/system-metrics/'
      preLoaderRoute: typeof AuthenticatedSystemMetricsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-tracking/': {
      id: '/_authenticated/tour-tracking/'
      path: '/tour-tracking'
      fullPath: '/tour-tracking/'
      preLoaderRoute: typeof AuthenticatedTourTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour-tracking/$tourId': {
      id: '/_authenticated/tour-tracking/$tourId'
      path: '/tour-tracking/$tourId'
      fullPath: '/tour-tracking/$tourId'
      preLoaderRoute: typeof AuthenticatedTourTrackingTourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tours/': {
      id: '/_authenticated/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof AuthenticatedToursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporter-contracts/': {
      id: '/_authenticated/transporter-contracts/'
      path: '/transporter-contracts'
      fullPath: '/transporter-contracts/'
      preLoaderRoute: typeof AuthenticatedTransporterContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/': {
      id: '/_authenticated/transporters/'
      path: '/transporters'
      fullPath: '/transporters/'
      preLoaderRoute: typeof AuthenticatedTransportersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters/$transporterId': {
      id: '/_authenticated/transporters/$transporterId'
      path: '/transporters/$transporterId'
      fullPath: '/transporters/$transporterId'
      preLoaderRoute: typeof AuthenticatedTransportersTransporterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks/': {
      id: '/_authenticated/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof AuthenticatedTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks/$truckId': {
      id: '/_authenticated/trucks/$truckId'
      path: '/trucks/$truckId'
      fullPath: '/trucks/$truckId'
      preLoaderRoute: typeof AuthenticatedTrucksTruckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/': {
      id: '/_authenticated/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof AuthenticatedVisitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/': {
      id: '/_authenticated/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof AuthenticatedZonesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/fleets/$fleetName': {
      id: '/_authenticated/dashboard/fleets/$fleetName'
      path: '/fleets/$fleetName'
      fullPath: '/dashboard/fleets/$fleetName'
      preLoaderRoute: typeof AuthenticatedDashboardFleetsFleetNameRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sites/$siteId': {
      id: '/_authenticated/dashboard/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/dashboard/sites/$siteId'
      preLoaderRoute: typeof AuthenticatedDashboardSitesSiteIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/super-admin/tours/': {
      id: '/_authenticated/super-admin/tours/'
      path: '/super-admin/tours'
      fullPath: '/super-admin/tours/'
      preLoaderRoute: typeof AuthenticatedSuperAdminToursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAnomaliesRouteChildren {
  AuthenticatedAnomaliesInvestigationRoute: typeof AuthenticatedAnomaliesInvestigationRoute
  AuthenticatedAnomaliesTechnicalRoute: typeof AuthenticatedAnomaliesTechnicalRoute
  AuthenticatedAnomaliesIndexRoute: typeof AuthenticatedAnomaliesIndexRoute
}

const AuthenticatedAnomaliesRouteChildren: AuthenticatedAnomaliesRouteChildren =
  {
    AuthenticatedAnomaliesInvestigationRoute:
      AuthenticatedAnomaliesInvestigationRoute,
    AuthenticatedAnomaliesTechnicalRoute: AuthenticatedAnomaliesTechnicalRoute,
    AuthenticatedAnomaliesIndexRoute: AuthenticatedAnomaliesIndexRoute,
  }

const AuthenticatedAnomaliesRouteWithChildren =
  AuthenticatedAnomaliesRoute._addFileChildren(
    AuthenticatedAnomaliesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardFleetsFleetNameRoute: typeof AuthenticatedDashboardFleetsFleetNameRoute
  AuthenticatedDashboardSitesSiteIdRoute: typeof AuthenticatedDashboardSitesSiteIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardFleetsFleetNameRoute:
      AuthenticatedDashboardFleetsFleetNameRoute,
    AuthenticatedDashboardSitesSiteIdRoute:
      AuthenticatedDashboardSitesSiteIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnomaliesRoute: typeof AuthenticatedAnomaliesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMarketersMarketerIdRoute: typeof AuthenticatedMarketersMarketerIdRoute
  AuthenticatedSettingsNotificationGroupsRoute: typeof AuthenticatedSettingsNotificationGroupsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedTourTrackingTourIdRoute: typeof AuthenticatedTourTrackingTourIdRoute
  AuthenticatedTransportersTransporterIdRoute: typeof AuthenticatedTransportersTransporterIdRoute
  AuthenticatedTrucksTruckIdRoute: typeof AuthenticatedTrucksTruckIdRoute
  AuthenticatedAlertRulesIndexRoute: typeof AuthenticatedAlertRulesIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedCertificatesIndexRoute: typeof AuthenticatedCertificatesIndexRoute
  AuthenticatedClientSitesIndexRoute: typeof AuthenticatedClientSitesIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCustomRolesIndexRoute: typeof AuthenticatedCustomRolesIndexRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
  AuthenticatedDashboardMarketeurIndexRoute: typeof AuthenticatedDashboardMarketeurIndexRoute
  AuthenticatedDashboardSupervisorIndexRoute: typeof AuthenticatedDashboardSupervisorIndexRoute
  AuthenticatedDashboardTransporteurIndexRoute: typeof AuthenticatedDashboardTransporteurIndexRoute
  AuthenticatedDeclarationsIndexRoute: typeof AuthenticatedDeclarationsIndexRoute
  AuthenticatedDepotsIndexRoute: typeof AuthenticatedDepotsIndexRoute
  AuthenticatedDeviceAssignmentsIndexRoute: typeof AuthenticatedDeviceAssignmentsIndexRoute
  AuthenticatedDeviceHealthIndexRoute: typeof AuthenticatedDeviceHealthIndexRoute
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedFirmwareIndexRoute: typeof AuthenticatedFirmwareIndexRoute
  AuthenticatedGpsConfigIndexRoute: typeof AuthenticatedGpsConfigIndexRoute
  AuthenticatedGpsTrackingIndexRoute: typeof AuthenticatedGpsTrackingIndexRoute
  AuthenticatedInfraIndexRoute: typeof AuthenticatedInfraIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
  AuthenticatedLivreursIndexRoute: typeof AuthenticatedLivreursIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedMapIndexRoute: typeof AuthenticatedMapIndexRoute
  AuthenticatedMarketersIndexRoute: typeof AuthenticatedMarketersIndexRoute
  AuthenticatedNotificationGroupsIndexRoute: typeof AuthenticatedNotificationGroupsIndexRoute
  AuthenticatedNotificationRulesIndexRoute: typeof AuthenticatedNotificationRulesIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedPasswordsIndexRoute: typeof AuthenticatedPasswordsIndexRoute
  AuthenticatedPerformanceIndexRoute: typeof AuthenticatedPerformanceIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedPickupTrackingIndexRoute: typeof AuthenticatedPickupTrackingIndexRoute
  AuthenticatedPickupsIndexRoute: typeof AuthenticatedPickupsIndexRoute
  AuthenticatedQuotasIndexRoute: typeof AuthenticatedQuotasIndexRoute
  AuthenticatedRecomputeIndexRoute: typeof AuthenticatedRecomputeIndexRoute
  AuthenticatedReconciliationsIndexRoute: typeof AuthenticatedReconciliationsIndexRoute
  AuthenticatedRedressementsIndexRoute: typeof AuthenticatedRedressementsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRfidTagsIndexRoute: typeof AuthenticatedRfidTagsIndexRoute
  AuthenticatedRiskScoresIndexRoute: typeof AuthenticatedRiskScoresIndexRoute
  AuthenticatedRisksIndexRoute: typeof AuthenticatedRisksIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSiteVerificationsIndexRoute: typeof AuthenticatedSiteVerificationsIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedSupplyIndexRoute: typeof AuthenticatedSupplyIndexRoute
  AuthenticatedSystemHealthIndexRoute: typeof AuthenticatedSystemHealthIndexRoute
  AuthenticatedSystemMetricsIndexRoute: typeof AuthenticatedSystemMetricsIndexRoute
  AuthenticatedTourTrackingIndexRoute: typeof AuthenticatedTourTrackingIndexRoute
  AuthenticatedToursIndexRoute: typeof AuthenticatedToursIndexRoute
  AuthenticatedTransporterContractsIndexRoute: typeof AuthenticatedTransporterContractsIndexRoute
  AuthenticatedTransportersIndexRoute: typeof AuthenticatedTransportersIndexRoute
  AuthenticatedTrucksIndexRoute: typeof AuthenticatedTrucksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
  AuthenticatedVisitsIndexRoute: typeof AuthenticatedVisitsIndexRoute
  AuthenticatedZonesIndexRoute: typeof AuthenticatedZonesIndexRoute
  AuthenticatedSuperAdminToursIndexRoute: typeof AuthenticatedSuperAdminToursIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnomaliesRoute: AuthenticatedAnomaliesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMarketersMarketerIdRoute: AuthenticatedMarketersMarketerIdRoute,
  AuthenticatedSettingsNotificationGroupsRoute:
    AuthenticatedSettingsNotificationGroupsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedTourTrackingTourIdRoute: AuthenticatedTourTrackingTourIdRoute,
  AuthenticatedTransportersTransporterIdRoute:
    AuthenticatedTransportersTransporterIdRoute,
  AuthenticatedTrucksTruckIdRoute: AuthenticatedTrucksTruckIdRoute,
  AuthenticatedAlertRulesIndexRoute: AuthenticatedAlertRulesIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedCertificatesIndexRoute: AuthenticatedCertificatesIndexRoute,
  AuthenticatedClientSitesIndexRoute: AuthenticatedClientSitesIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCustomRolesIndexRoute: AuthenticatedCustomRolesIndexRoute,
  AuthenticatedDashboardAdminIndexRoute: AuthenticatedDashboardAdminIndexRoute,
  AuthenticatedDashboardMarketeurIndexRoute:
    AuthenticatedDashboardMarketeurIndexRoute,
  AuthenticatedDashboardSupervisorIndexRoute:
    AuthenticatedDashboardSupervisorIndexRoute,
  AuthenticatedDashboardTransporteurIndexRoute:
    AuthenticatedDashboardTransporteurIndexRoute,
  AuthenticatedDeclarationsIndexRoute: AuthenticatedDeclarationsIndexRoute,
  AuthenticatedDepotsIndexRoute: AuthenticatedDepotsIndexRoute,
  AuthenticatedDeviceAssignmentsIndexRoute:
    AuthenticatedDeviceAssignmentsIndexRoute,
  AuthenticatedDeviceHealthIndexRoute: AuthenticatedDeviceHealthIndexRoute,
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedFirmwareIndexRoute: AuthenticatedFirmwareIndexRoute,
  AuthenticatedGpsConfigIndexRoute: AuthenticatedGpsConfigIndexRoute,
  AuthenticatedGpsTrackingIndexRoute: AuthenticatedGpsTrackingIndexRoute,
  AuthenticatedInfraIndexRoute: AuthenticatedInfraIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  AuthenticatedLivreursIndexRoute: AuthenticatedLivreursIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedMapIndexRoute: AuthenticatedMapIndexRoute,
  AuthenticatedMarketersIndexRoute: AuthenticatedMarketersIndexRoute,
  AuthenticatedNotificationGroupsIndexRoute:
    AuthenticatedNotificationGroupsIndexRoute,
  AuthenticatedNotificationRulesIndexRoute:
    AuthenticatedNotificationRulesIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedPasswordsIndexRoute: AuthenticatedPasswordsIndexRoute,
  AuthenticatedPerformanceIndexRoute: AuthenticatedPerformanceIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedPickupTrackingIndexRoute: AuthenticatedPickupTrackingIndexRoute,
  AuthenticatedPickupsIndexRoute: AuthenticatedPickupsIndexRoute,
  AuthenticatedQuotasIndexRoute: AuthenticatedQuotasIndexRoute,
  AuthenticatedRecomputeIndexRoute: AuthenticatedRecomputeIndexRoute,
  AuthenticatedReconciliationsIndexRoute:
    AuthenticatedReconciliationsIndexRoute,
  AuthenticatedRedressementsIndexRoute: AuthenticatedRedressementsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRfidTagsIndexRoute: AuthenticatedRfidTagsIndexRoute,
  AuthenticatedRiskScoresIndexRoute: AuthenticatedRiskScoresIndexRoute,
  AuthenticatedRisksIndexRoute: AuthenticatedRisksIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSiteVerificationsIndexRoute:
    AuthenticatedSiteVerificationsIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedSupplyIndexRoute: AuthenticatedSupplyIndexRoute,
  AuthenticatedSystemHealthIndexRoute: AuthenticatedSystemHealthIndexRoute,
  AuthenticatedSystemMetricsIndexRoute: AuthenticatedSystemMetricsIndexRoute,
  AuthenticatedTourTrackingIndexRoute: AuthenticatedTourTrackingIndexRoute,
  AuthenticatedToursIndexRoute: AuthenticatedToursIndexRoute,
  AuthenticatedTransporterContractsIndexRoute:
    AuthenticatedTransporterContractsIndexRoute,
  AuthenticatedTransportersIndexRoute: AuthenticatedTransportersIndexRoute,
  AuthenticatedTrucksIndexRoute: AuthenticatedTrucksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
  AuthenticatedVisitsIndexRoute: AuthenticatedVisitsIndexRoute,
  AuthenticatedZonesIndexRoute: AuthenticatedZonesIndexRoute,
  AuthenticatedSuperAdminToursIndexRoute:
    AuthenticatedSuperAdminToursIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
